/** 2026/27 BPS weights. The API does not expose these; sourced from published rules.
 *  ASSUMPTION — verify against real data (task 2.9) and correct here if needed. */
export const BPS = {
  playUpTo60: 3,
  playOver60: 6,
  goal: { 1: 12, 2: 12, 3: 18, 4: 24 } as Record<number, number>,
  assist: 9,
  cleanSheet: { 1: 12, 2: 12, 3: 0, 4: 0 } as Record<number, number>,
  save: 2,
  saveInBox: 1,
  bigChanceSave: 1,
  penSave: 7,
  cbiPerN: 3,
  recoveryPerN: 3,
  keyPass: 1,
  bigChanceCreated: 3,
  openPlayCross: 1,
  successfulDribble: 1,
  shotOnTarget: 2,
  matchWinningGoal: 3,
  goallineClearance: 3,
  foulWon: 1,
  tackleWon: 2,
  tackled: 0,
  passCompletion: { "70-79": 2, "80-89": 4, "90+": 6 } as Record<string, number>,
  concededGkDef: -4,
  penConceded: -3,
  penMissed: -6,
  yellow: -3,
  red: -9,
  ownGoal: -6,
  bigChanceMissed: -3,
  errorLeadingToGoal: -3,
  errorLeadingToAttempt: -1,
  foulConceded: -1,
  offside: -1,
  shotOffTarget: -1,
} as const;
